/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import java.util.*;

public class App {
    public static void main(String[] args) {
        List<List<Object>> example = new ArrayList<>();
        example.add(Arrays.asList("a", "b", "c"));
        example.add(Arrays.asList("1", "2", "3"));

        ExcelWriter.on("sheet1", example).write();
    }
}
