/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.arrow;

import java.sql.DriverManager;

import org.apache.arrow.adapter.jdbc.JdbcToArrow;
import org.apache.arrow.memory.RootAllocator;

public class App {
    public static void main(String[] args) {
        try (var allocator = new RootAllocator();
             var conn = DriverManager.getConnection("jdbc:h2:mem:testdb")) {
            try (var st = conn.createStatement()) {
                // 创建表
                st.execute("CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, name VARCHAR(255))");
                st.execute("INSERT INTO users (id, name) VALUES (1, 'Alice')");
                st.execute("INSERT INTO users (id, name) VALUES (2, 'Bob')");
                st.execute("INSERT INTO users (id, name) VALUES (3, 'Carol')");

                // 查询所有数据
                var r = st.executeQuery("SELECT * FROM users");

                // 使用 Adapter 将数据装到 arrow 结构体中
                try (var it = JdbcToArrow.sqlToArrowVectorIterator(r, allocator)) {
                    while (it.hasNext()) {
                        try (var root = it.next()) {
                            System.out.println("id: " + root.getVector("ID"));
                            System.out.println("name: " + root.getVector("NAME"));
                        }
                    }
                } finally {
                    r.close();
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
}
