/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import java.util.List;

public class App {

    public static void main(String[] args) {
        Table a = new Table();
        a.setId(1);
        a.setName("A");

        Table b = new Table();
        b.setId(2);
        b.setName("B");

        Table c = new Table();
        c.setId(3);
        c.setName("C");

        Table d = new Table();
        d.setId(4);
        d.setName("D");

        Relationship r1 = new Relationship();
        r1.setId(1);
        r1.setLeftTableId(a.getId());
        r1.setRightTableId(b.getId());

        Relationship r2 = new Relationship();
        r2.setId(2);
        r2.setLeftTableId(b.getId());
        r2.setRightTableId(d.getId());

        Relationship r3 = new Relationship();
        r3.setId(3);
        r3.setLeftTableId(a.getId());
        r3.setRightTableId(c.getId());

        Relationship r4 = new Relationship();
        r4.setId(4);
        r4.setLeftTableId(c.getId());
        r4.setRightTableId(d.getId());

        Table[] tables = new Table[] {a, b, c, d};
        Relationship[] relationships = new Relationship[] {r1, r2, r3, r4};

        MetaSet metaSet = new MetaSet(tables, relationships);

        List<Table> shortestPath = metaSet.shortestPath(a, d);
        for (Table table : shortestPath) {
            System.out.println(table.getName());
        }
    }
}
