/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import java.io.IOException;

import okhttp3.MediaType;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;

public class App {
    public static final MediaType APPLICATION_JSON = MediaType.get("application/json");

    public static void main(String[] args) {
        OkHttpClient client = new OkHttpClient();

        // Request body.
        String content = "{\"name\":\"admin\"}";
        RequestBody body = RequestBody.create(content, APPLICATION_JSON);

        Request request = new Request.Builder()
            .url("http://localhost:8080")
            .post(body)
            .build();
        try (Response response = client.newCall(request).execute()) {
            if (response.isSuccessful()) {
                System.out.println(response.body().string());
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
